### PR TITLE
API fixes and cleanup

### PR DESCRIPTION
**Pull request by bouchard**
Hello,

I had some contact with SRFax technical support. They require that any JSON variables are encoded in the same hash, rather than as separate post variables as was done before. This allowed me to simplify the use of RestClient significantly.

I've also added a (very basic) test, and cleaned the source with rubocop. In the short-term, I have distributed the gem under the `srfax` name rather than `sr_fax`, as we're using this in production and are trying not to rely on Github for gem pulls.

Let me know if you'd like me to modify anything before merge.

### CODE REVIEW

**Comment by bouchard** [comment]
I've noticed a few obvious things you wouldn't want to merge (like reference to my Github repo). Let me know if you're interested in these changes at all, and I'll modify this PR if so.

**Comment by TechCanuck** [comment]
Thanks brady, alot of basic style changes and a good update for Rubocop as well.  If you can just modify the github reference back I'll merge and push without issue.

**Comment by bouchard** [comment]
Ready to go!

**Comment by TechCanuck** [comment]
https://rubygems.org/gems/sr_fax - 0.5.3 published

**Pull request merged**
